import { Lead } from "./types";

export const DEFAULT_DATA: Lead[] = [
  {
    name: "Gasthaus Zum Goldenen Hirsch",
    phone: "+49 89 12345678",
    website: "",
    address: "Marienplatz 12",
    city: "München",
    postal: "80331",
    rating: 4.5,
    reviews: 23,
    category: "Restaurant",
    subtypes: "Bayerische Küche, Biergarten",
    photo: "",
    description: "Traditionelles bayerisches Gasthaus mit Biergarten",
    verified: true,
  },
  {
    name: "Pizzeria Bella Italia",
    phone: "+49 89 87654321",
    website: "https://bella-italia-muenchen.de",
    address: "Leopoldstraße 45",
    city: "München",
    postal: "80802",
    rating: 4.2,
    reviews: 156,
    category: "Restaurant",
    subtypes: "Italienisch, Pizza, Pasta",
    photo: "",
    description: "Authentische italienische Küche seit 1998",
    verified: true,
  },
  {
    name: "Asia Wok Express",
    phone: "+49 89 55667788",
    website: "",
    address: "Sendlinger Straße 8",
    city: "München",
    postal: "80331",
    rating: 3.8,
    reviews: 45,
    category: "Restaurant",
    subtypes: "Asiatisch, Wok, Lieferdienst",
    photo: "",
    description: "",
    verified: false,
  },
  {
    name: "Café Morgentau",
    phone: "",
    website: "",
    address: "Türkenstraße 22",
    city: "München",
    postal: "80799",
    rating: 4.7,
    reviews: 12,
    category: "Café",
    subtypes: "Frühstück, Kaffee, Kuchen",
    photo: "",
    description: "Gemütliches Café mit hausgemachten Kuchen",
    verified: true,
  },
  {
    name: "Burger Palace",
    phone: "+49 89 33445566",
    website: "https://burger-palace.de",
    address: "Schillerstraße 3",
    city: "München",
    postal: "80336",
    rating: 4.0,
    reviews: 89,
    category: "Restaurant",
    subtypes: "Burger, Fast Food, Amerikanisch",
    photo: "",
    description: "Premium Burger und Craft Beer",
    verified: true,
  },
  {
    name: "Taverna Olympia",
    phone: "+49 89 99887766",
    website: "",
    address: "Amalienstraße 67",
    city: "München",
    postal: "80799",
    rating: 4.3,
    reviews: 34,
    category: "Restaurant",
    subtypes: "Griechisch, Mediterran",
    photo: "",
    description: "Griechische Spezialitäten und Ouzo",
    verified: true,
  },
  {
    name: "Sushi Meister Tanaka",
    phone: "+49 89 11223344",
    website: "https://sushi-tanaka.de",
    address: "Maximilianstraße 15",
    city: "München",
    postal: "80539",
    rating: 4.8,
    reviews: 210,
    category: "Restaurant",
    subtypes: "Japanisch, Sushi, Fine Dining",
    photo: "",
    description: "Authentisches japanisches Sushi-Restaurant",
    verified: true,
  },
  {
    name: "Döner König",
    phone: "+49 89 77665544",
    website: "",
    address: "Sonnenstraße 29",
    city: "München",
    postal: "80331",
    rating: 4.1,
    reviews: 8,
    category: "Imbiss",
    subtypes: "Döner, Türkisch, Schnellimbiss",
    photo: "",
    description: "",
    verified: false,
  },
  {
    name: "Brauhaus Augustiner",
    phone: "+49 89 44556677",
    website: "https://augustiner-brauhaus.de",
    address: "Neuhauser Straße 27",
    city: "München",
    postal: "80331",
    rating: 4.6,
    reviews: 432,
    category: "Brauhaus",
    subtypes: "Bayerisch, Bier, Biergarten",
    photo: "",
    description: "Traditionsbrauhaus mit eigener Brauerei",
    verified: true,
  },
  {
    name: "Eiscafé Venezia",
    phone: "+49 89 22334455",
    website: "",
    address: "Hohenzollernstraße 11",
    city: "München",
    postal: "80801",
    rating: 4.4,
    reviews: 67,
    category: "Eiscafé",
    subtypes: "Eis, Dessert, Kaffee",
    photo: "",
    description: "Handgemachtes italienisches Eis",
    verified: true,
  },
  {
    name: "Thai Orchidee",
    phone: "+49 89 66778899",
    website: "",
    address: "Dachauerstraße 52",
    city: "München",
    postal: "80335",
    rating: 3.9,
    reviews: 19,
    category: "Restaurant",
    subtypes: "Thailändisch, Curry, Asiatisch",
    photo: "",
    description: "Authentische thailändische Küche",
    verified: true,
  },
  {
    name: "Steakhouse El Gaucho",
    phone: "+49 89 55443322",
    website: "https://elgaucho-muenchen.de",
    address: "Brienner Straße 44",
    city: "München",
    postal: "80333",
    rating: 4.3,
    reviews: 178,
    category: "Restaurant",
    subtypes: "Steakhouse, Argentinisch, Grill",
    photo: "",
    description: "Argentinische Steaks vom Holzkohlegrill",
    verified: true,
  },
];
